/**
 * Capability Registry seed values.
 *
 * IMPORTANT: All cost, latency and intent-score values below are PROPOSAL
 * values, not measurements. They exist so the Routing Engine has something
 * to score against on day one. The Learning Engine (Phase 4 — see
 * docs/KERNEL.md §10) will refine `successRate` / `retryRate` from real
 * traffic, and a founder review pass can adjust the intent scores based
 * on observed quality.
 *
 * The shape of each row MUST match `CapabilitySeed` in
 * ./capability-registry.types.ts AND the field names read by
 * scripts/seed-capabilities.ts. The seed script reads by name (seed.inputCostPer1M,
 * seed.largeContextWindow, etc.), so renames here will break seeding.
 */
import type { CapabilitySeed } from './capability-registry.types';

export const CAPABILITY_SEEDS: CapabilitySeed[] = [
  {
    provider: 'glm',
    model: 'glm-5.2',
    displayName: 'GLM 5.2',
    inputCostPer1M: 0.5,
    outputCostPer1M: 1.5,
    latencyP50Ms: 1500,
    codeScore: 0.95,
    reasoningScore: 0.85,
    simpleQaScore: 0.8,
    agentScore: 0.75,
    visionScore: 0.0,
    toolUse: true,
    jsonMode: true,
    largeContext: false,
    largeContextWindow: null,
  },
  {
    provider: 'glm',
    model: 'glm-4.6',
    displayName: 'GLM 4.6',
    inputCostPer1M: 0.2,
    outputCostPer1M: 0.6,
    latencyP50Ms: 1200,
    codeScore: 0.8,
    reasoningScore: 0.65,
    simpleQaScore: 0.75,
    agentScore: 0.55,
    visionScore: 0.0,
    toolUse: false,
    jsonMode: true,
    largeContext: true,
    largeContextWindow: 200000,
  },
  {
    provider: 'deepseek',
    model: 'deepseek-coder-v2',
    displayName: 'DeepSeek Coder V2',
    inputCostPer1M: 0.2,
    outputCostPer1M: 0.6,
    latencyP50Ms: 1000,
    codeScore: 0.92,
    reasoningScore: 0.7,
    simpleQaScore: 0.7,
    agentScore: 0.6,
    visionScore: 0.0,
    toolUse: false,
    jsonMode: true,
    largeContext: false,
    largeContextWindow: null,
  },
  {
    provider: 'deepseek',
    model: 'deepseek-reasoner',
    displayName: 'DeepSeek Reasoner',
    inputCostPer1M: 0.3,
    outputCostPer1M: 0.9,
    latencyP50Ms: 2200,
    codeScore: 0.75,
    reasoningScore: 0.95,
    simpleQaScore: 0.7,
    agentScore: 0.7,
    visionScore: 0.0,
    toolUse: false,
    jsonMode: true,
    largeContext: false,
    largeContextWindow: null,
  },
  {
    provider: 'deepseek',
    model: 'deepseek-chat',
    displayName: 'DeepSeek Chat',
    inputCostPer1M: 0.15,
    outputCostPer1M: 0.45,
    latencyP50Ms: 900,
    codeScore: 0.78,
    reasoningScore: 0.55,
    simpleQaScore: 0.65,
    agentScore: 0.45,
    visionScore: 0.0,
    toolUse: false,
    jsonMode: true,
    largeContext: false,
    largeContextWindow: null,
  },
  {
    provider: 'kimi',
    model: 'kimi-coder',
    displayName: 'Kimi Coder',
    inputCostPer1M: 0.15,
    outputCostPer1M: 0.45,
    latencyP50Ms: 900,
    codeScore: 0.78,
    reasoningScore: 0.55,
    simpleQaScore: 0.65,
    agentScore: 0.45,
    visionScore: 0.0,
    toolUse: false,
    jsonMode: true,
    largeContext: false,
    largeContextWindow: null,
  },
  {
    provider: 'kimi',
    model: 'kimi-k2',
    displayName: 'Kimi K2',
    inputCostPer1M: 0.6,
    outputCostPer1M: 2.5,
    latencyP50Ms: 1800,
    codeScore: 0.85,
    reasoningScore: 0.92,
    simpleQaScore: 0.8,
    agentScore: 0.82,
    visionScore: 0.0,
    toolUse: true,
    jsonMode: true,
    largeContext: true,
    largeContextWindow: 200000,
  },
];
