#!/usr/bin/env python3
"""Lightweight pathway scorecard loader — bot dashboard only (no order logic)."""
from __future__ import annotations

import json
import os
import time

SCORECARD_FILE = "pathway_scorecard.json"
STALE_SEC = 3600


def _scorecard_path(cwd: str) -> str:
    for base in (cwd, os.path.join(cwd, "research")):
        path = os.path.join(base, SCORECARD_FILE)
        if os.path.isfile(path):
            return path
    return os.path.join(cwd, SCORECARD_FILE)


def load_pathway_scorecard(cwd: str | None = None) -> dict:
    cwd = cwd or os.getcwd()
    path = _scorecard_path(cwd)
    if not os.path.isfile(path):
        return {}
    try:
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
        return data if isinstance(data, dict) else {}
    except Exception:
        return {}


def scorecard_is_stale(cwd: str | None = None) -> bool:
    cwd = cwd or os.getcwd()
    path = _scorecard_path(cwd)
    if not os.path.isfile(path):
        return True
    try:
        return (time.time() - os.path.getmtime(path)) > STALE_SEC
    except OSError:
        return True


def refresh_pathway_scorecard(
    cwd: str | None = None,
    *,
    bot_version: str = "",
    lanes_live: dict | None = None,
    fresh_collection_mode: bool = False,
) -> dict:
    """Bot-side refresh is read-only — analyzer owns scorecard generation."""
    loaded = load_pathway_scorecard(cwd)
    if loaded:
        return loaded
    return {
        "schema": "pathway_scorecard_stub_v1",
        "bot_version": bot_version,
        "fresh_collection_mode": fresh_collection_mode,
        "note": "Scorecard generated by analyzer — run research loop on :9500",
        "lanes_live": lanes_live or {},
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }
