"""Bounded reset rejection codes; never publish exception text or filesystem paths."""
from research_exact_deletion import ResearchDeletionRejected


REJECTION_CODES = frozenset("""
PATH_OUTSIDE_EXPLICIT_ROOT SYMLINK_OR_REPARSE_POINT PATH_RESOLUTION_CHANGED
TARGET_NOT_REGULAR_FILE TARGET_CHANGED_WHILE_HASHING RECEIPT_LIMIT_EXCEEDED
RECEIPT_PATH_IDENTITY_MISMATCH INVALID_RECEIPT_INVENTORY JOURNAL_IDENTITY_MISMATCH
JOURNAL_SEED_MISMATCH JOURNAL_INCOMPLETE_OR_OVERSIZED JOURNAL_HASH_MISMATCH
JOURNAL_SEQUENCE_INVALID QUIESCENCE_NOT_PROVEN RECOVERY_NOT_RECONCILED
RECOVERY_PROOF_KEY_INVALID INVALID_RECEIPT_CONTEXT INVALID_RECEIPT_CONTEXT_IDENTITY
INVALID_RETAINED_METADATA INVALID_RETAINED_ALIAS_TARGET RECEIPT_CONTEXT_LIMIT_EXCEEDED
UNSAFE_ROOT ROOT_SYMLINK_OR_REPARSE_POINT INVALID_FILE_LIMIT INVALID_BYTE_LIMIT
FILE_LIMIT_EXCEEDED ALLOWLIST_LIMIT_EXCEEDED PROTECTED_LIST_LIMIT_EXCEEDED
UNSAFE_RECEIPT_PATH UNSAFE_PROGRESS_PATH TARGET_NOT_ALLOWLISTED PROTECTED_PATH
PROTECTED_SOURCE_OR_RECOVERY BYTE_LIMIT_EXCEEDED INVALID_EXPECTED_HASH_MAP
INVALID_EXPECTED_HASH_BINDING AMBIGUOUS_EXPECTED_HASH_BINDING EXPECTED_SHA256_MISMATCH
TARGET_CHANGED_BEFORE_DELETE VALIDATE_ONLY_REQUIRES_BOOLEAN RESET_INVENTORY_INCOMPLETE
RESET_BOUNDARY_PROOF_INVALID RESET_PLAN_CHANGED RESET_TARGET_BUDGET_EXCEEDED
RESET_TARGET_CHANGED_AFTER_PLAN RESET_TARGET_CHANGED_DURING_VALIDATION
ARCHIVE_EXPECTED_HASH_MISSING ARCHIVE_SHA256_MISMATCH RESET_PHYSICAL_SCOPE_CHANGED
""".split())


def reset_failure_fields(error):
    """Add an exact static code alongside the existing exception class field."""
    result = {"error": type(error).__name__}
    if isinstance(error, ResearchDeletionRejected):
        code = error.args[0] if len(error.args) == 1 else None
        result["rejection_code"] = (code if isinstance(code, str) and code in REJECTION_CODES
                                    else "UNCLASSIFIED_RESEARCH_DELETION_REJECTION")
    return result
