/**
 * Founder IDE IPC protocol contract (Phase 3).
 *
 * This file is the canonical contract for the named-pipe IPC channel between
 * the Founder IDE extension (VS Code / Cursor / VSCodium) and the Founder Node
 * tray adapter. Workstream B implements the wire layer against these types;
 * Workstream C surfaces status derived from these messages; Workstream E does
 * not touch IPC directly.
 *
 * Design notes:
 * - Every request/response carries a `nonce` for replay protection. The
 *   `NonceTracker` class below is the reference implementation for the
 *   replay window. Both sides MUST run a tracker.
 * - The protocol is a discriminated union on `type`. Switch exhaustiveness is
 *   enforced by the compiler via `never` in the dispatcher default branch.
 * - "Request" messages expect a response with a matching `nonce`. "Event"
 *   messages are fire-and-forget. The split lets the adapter decide whether
 *   to await an acknowledgement before progressing.
 * - Capabilities are advertised in `hello` so the adapter can downgrade
 *   gracefully when an older extension (e.g. stock VS Code without the
 *   proposed API) connects. Unknown capabilities MUST be ignored — forward
 *   compatibility is the rule.
 *
 * Transport: Windows named pipe `\\.\pipe\founder-ide-{installId}`. The
 * installId is generated by the extension on first launch and stored in
 * node-config.json; the tray reads it from the paired node row. The IPC
 * secret (also in node-config.json) is presented in plaintext during
 * `hello` and verified by the adapter via bcrypt.compare against the stored
 * hash. If the secret mismatches, the adapter closes the pipe without
 * responding — the extension treats that as `authState = revoked`.
 */

/**
 * Bumped on every breaking change to this file. Both sides MUST refuse to
 * talk to a peer whose `protocolVersion` differs by more than they can
 * tolerate. v1 is the initial Phase 3 release.
 */
export const IPC_PROTOCOL_VERSION = 1 as const;

/**
 * Capabilities the extension advertises in `hello`. The adapter uses these to
 * decide which messages to send — e.g. it won't emit `openFiles` unless the
 * extension advertised `openFiles`. The set is open: unknown capabilities
 * MUST be ignored (forward compat).
 */
export type IpcCapability =
  | 'workspace'
  | 'openFiles'
  | 'selection'
  | 'taskState'
  | 'chatPrompt'
  | 'chatPromptResult'
  | 'workspaceReadRequest'
  | 'workspaceReadResult'
  | 'proposedEdit'
  | 'editReviewResult'
  | 'commandRequest'
  | 'commandReviewResult'
  | 'commandOutput'
  | 'cancel'
  | 'gatewayHealth'
  | 'memoryHealth'
  | 'versionState'
  | 'companionState'
  | 'companionAction'
  | 'heartbeat';

/** Auth states the extension can report. Mirrors `PairingState` in founder-vault. */
export type IpcAuthStateValue =
  | 'not_paired'
  | 'pairing'
  | 'paired_gateway_unreachable'
  | 'connected'
  | 'token_expired'
  | 'revoked';

/** Common fields on every message. */
interface IpcEnvelope {
  /** Random 16+ byte hex string. Unique per request; echoed in the response. */
  nonce: string;
  /** ISO timestamp the sender emitted the message. Used for staleness, not auth. */
  ts: string;
}

// ---------------------------------------------------------------------------
// Message types (one per capability + the handshake/auth set)
// ---------------------------------------------------------------------------

/**
 * First message after the pipe connects. The extension presents its
 * `installId` + plaintext `ipcSecret` so the adapter can authenticate the
 * pipe. The adapter verifies the secret (bcrypt.compare against the stored
 * hash) and either starts emitting events or closes the pipe.
 *
 * `capabilities` is the full set the extension supports — the adapter
 * intersects with its own supported set and only emits messages the extension
 * advertised.
 */
export interface IpcHello extends IpcEnvelope {
  type: 'hello';
  protocolVersion: typeof IPC_PROTOCOL_VERSION;
  installId: string;
  /** Plaintext IPC secret from node-config.json. Compared against stored hash. */
  ipcSecret: string;
  capabilities: IpcCapability[];
}

/** Adapter emits this whenever the auth/pairing state changes. */
export interface IpcAuthState extends IpcEnvelope {
  type: 'authState';
  state: IpcAuthStateValue;
  /** Human-readable reason for the transition (for the tray status panel). */
  reason?: string;
}

/** Active workspace context. Emitted on workspace change + every heartbeat. */
export interface IpcWorkspace extends IpcEnvelope {
  type: 'workspace';
  /** Absolute path to the workspace root, or null if no folder is open. */
  workspacePath: string | null;
  /** Git remote URL if known, else null. */
  repository: string | null;
  /** Current git branch, or null if not a git repo. */
  branch: string | null;
}

/**
 * List of currently-open files. ONLY emitted when the user has consented to
 * "share open files with Founder OS" — the adapter MUST NOT request this
 * unless consent is recorded. Filenames only, no contents.
 */
export interface IpcOpenFiles extends IpcEnvelope {
  type: 'openFiles';
  files: Array<{
    /** Workspace-relative path. */
    path: string;
    /** Active editor language id (typescript, python, markdown, …). */
    languageId?: string;
    /** True if this is the currently-focused editor. */
    active?: boolean;
  }>;
}

/**
 * Current text selection. ONLY emitted when consented. Truncated to 4 KiB to
 * avoid piping megabytes of selection into the IPC channel.
 */
export interface IpcSelection extends IpcEnvelope {
  type: 'selection';
  path: string | null;
  languageId?: string;
  text: string;
  startLine: number;
  endLine: number;
}

/** Active task + agent state. Emitted on state change + heartbeat. */
export interface IpcTaskState extends IpcEnvelope {
  type: 'taskState';
  /** Opaque task id assigned by the gateway, or null if no task is active. */
  taskId: string | null;
  /** Free-text label (the user's prompt or task title). */
  label: string | null;
  /** Current agent phase. */
  phase: 'idle' | 'thinking' | 'editing' | 'running_command' | 'waiting_review' | 'done' | 'error';
  /** ISO timestamp the current phase started. */
  phaseStartedAt?: string;
}

/**
 * Prompt sent from Founder OS on another device to the paired Founder IDE.
 * The extension opens the built-in chat surface and submits the prompt to the
 * FounderOS participant, so the user can watch the agent work locally.
 */
import { randomBytes } from 'node:crypto';
export interface IpcChatPrompt extends IpcEnvelope {
  type: 'chatPrompt';
  requestId: string;
  prompt: string;
  /** Optional remote session id for attribution and deduplication. */
  sessionId?: string;
}

export interface IpcChatPromptResult extends IpcEnvelope {
  type: 'chatPromptResult';
  requestId: string;
  delivered: boolean;
  error?: string;
}

export interface IpcWorkspaceReadRequest extends IpcEnvelope {
  type: 'workspaceReadRequest';
  requestId: string;
  path?: string;
  maxEntries?: number;
}

export interface IpcWorkspaceReadResult extends IpcEnvelope {
  type: 'workspaceReadResult';
  requestId: string;
  nodes: Array<{
    path: string;
    name: string;
    type: 'file' | 'directory';
    sizeBytes?: number;
    modifiedAt?: string;
  }>;
  error?: string;
}

/**
 * Proposed file edit sent for human review BEFORE being applied. The
 * extension renders a diff view and asks the user to approve/reject. The
 * adapter awaits `editReviewResult` before progressing the task.
 */
export interface IpcProposedEdit extends IpcEnvelope {
  type: 'proposedEdit';
  /** The request this edit is answering. */
  requestId: string;
  path: string;
  /** Unified diff (one-line header + hunks). */
  diff: string;
  /** Whether the edit creates the file. */
  creates: boolean;
  /** Structured edit payload. New peers should prefer this over parsing diff. */
  edit?: {
    kind: 'create' | 'overwrite' | 'append' | 'patch';
    content: string;
    anchor?: string;
  };
}

/** Response to a `proposedEdit`. `approved=false` halts the task. */
export interface IpcEditReviewResult extends IpcEnvelope {
  type: 'editReviewResult';
  /** Matches the `proposedEdit` `requestId`. */
  requestId: string;
  approved: boolean;
  /** Free-text reason (user feedback, "wrong file", etc). */
  reason?: string;
}

/**
 * Terminal command the adapter wants to run. The extension shows it to the
 * user for approval. High-risk commands (rm, force-push, db drop) MUST be
 * surfaced for explicit approval; safe read-only commands may be auto-approved
 * per user setting.
 */
export interface IpcCommandRequest extends IpcEnvelope {
  type: 'commandRequest';
  requestId: string;
  command: string;
  cwd?: string;
  /** Hint for the UI to decide auto-approve vs. prompt. */
  risk: 'readonly' | 'mutation' | 'destructive';
  /** Max milliseconds the adapter will wait before treating it as a timeout. */
  timeoutMs?: number;
}

/** Response to a `commandRequest`. */
export interface IpcCommandReviewResult extends IpcEnvelope {
  type: 'commandReviewResult';
  requestId: string;
  approved: boolean;
  reason?: string;
}

/**
 * Streaming stdout/stderr for an approved command. May be multiple messages
 * for a long-running command. A final message with `exitCode` set terminates
 * the stream.
 */
export interface IpcCommandOutput extends IpcEnvelope {
  type: 'commandOutput';
  requestId: string;
  stream: 'stdout' | 'stderr';
  chunk: string;
  /** Present only on the final chunk. Null means more output is coming. */
  exitCode?: number | null;
}

/** Cancel the in-flight task/request referenced by `requestId` (or task id). */
export interface IpcCancel extends IpcEnvelope {
  type: 'cancel';
  /** Task or request id to cancel. */
  requestId?: string;
  taskId?: string;
  reason?: string;
}

/** Gateway health snapshot. Emitted on change + every heartbeat. */
export interface IpcGatewayHealth extends IpcEnvelope {
  type: 'gatewayHealth';
  reachable: boolean;
  /** HTTP status of the last probe, or null if unreachable. */
  lastStatus?: number | null;
  /** Latency of the last successful probe, in ms. */
  latencyMs?: number | null;
  /** ISO timestamp of the last successful probe. */
  lastSuccessAt?: string;
}

/** Memory engine health snapshot. */
export interface IpcMemoryHealth extends IpcEnvelope {
  type: 'memoryHealth';
  /** Vault file present + parseable. */
  healthy: boolean;
  /** Number of chunks indexed. */
  vectorChunks: number;
  /** Whether the local Ollama embedding model is reachable. */
  embeddingReachable: boolean;
  lastError?: string;
}

/** Version + updater state. Emitted on state change. */
export interface IpcVersionState extends IpcEnvelope {
  type: 'versionState';
  installedVersion: string;
  latestVersion: string;
  /** Whether an update is available (installedVersion !== latestVersion). */
  updateAvailable: boolean;
  updateState: 'idle' | 'downloading' | 'verifying' | 'installing' | 'rolling_back' | 'failed';
}

/** Transparent desktop companion state emitted by the IDE extension. */
export interface IpcCompanionState extends IpcEnvelope {
  type: 'companionState';
  visible: boolean;
  state:
    | 'idle'
    | 'listening'
    | 'planning'
    | 'working'
    | 'coordinating'
    | 'verifying'
    | 'success'
    | 'attention'
    | 'error'
    | 'offline'
    | 'update';
  title: string;
  detail: string;
  reducedMotion: boolean;
}

/** User action from the desktop Dragon back to the owning IDE. */
export interface IpcCompanionAction extends IpcEnvelope {
  type: 'companionAction';
  action:
    | 'openTask'
    | 'openUsage'
    | 'openSettings'
    | 'hide'
    | 'toggleReducedMotion'
    | 'signOut';
}

/** Heartbeat — both sides emit this every 15s to keep the pipe alive. */
export interface IpcHeartbeat extends IpcEnvelope {
  type: 'heartbeat';
  /** ISO timestamp of the heartbeat. */
  at: string;
}

// ---------------------------------------------------------------------------
// Unions
// ---------------------------------------------------------------------------

/** Every IPC message. Discriminated union on `type`. */
export type IpcMessage =
  | IpcHello
  | IpcAuthState
  | IpcWorkspace
  | IpcOpenFiles
  | IpcSelection
  | IpcTaskState
  | IpcChatPrompt
  | IpcChatPromptResult
  | IpcWorkspaceReadRequest
  | IpcWorkspaceReadResult
  | IpcProposedEdit
  | IpcEditReviewResult
  | IpcCommandRequest
  | IpcCommandReviewResult
  | IpcCommandOutput
  | IpcCancel
  | IpcGatewayHealth
  | IpcMemoryHealth
  | IpcVersionState
  | IpcCompanionState
  | IpcCompanionAction
  | IpcHeartbeat;

/**
 * Messages that expect a response. The adapter (or extension) MUST reply with
 * a message carrying the same `nonce`. The set is the intersection of
 * "request-like" shapes — proposedEdit (expects editReviewResult),
 * commandRequest (expects commandReviewResult), hello (expects authState or
 * pipe close). Everything else is fire-and-forget.
 */
export type IpcRequest =
  | IpcHello
  | IpcChatPrompt
  | IpcWorkspaceReadRequest
  | IpcProposedEdit
  | IpcCommandRequest;

/**
 * Messages that respond to a request. `editReviewResult` answers
 * `proposedEdit`; `commandReviewResult` answers `commandRequest`. `hello` is
 * answered implicitly by `authState` (the adapter emits authState once it
 * has verified the secret).
 */
export type IpcResponse =
  | IpcAuthState
  | IpcChatPromptResult
  | IpcWorkspaceReadResult
  | IpcEditReviewResult
  | IpcCommandReviewResult;

/**
 * Fire-and-forget events. Neither side awaits a response. This is the
 * complement of (IpcRequest ∪ IpcResponse) within IpcMessage.
 */
export type IpcEvent =
  | IpcWorkspace
  | IpcOpenFiles
  | IpcSelection
  | IpcTaskState
  | IpcCommandOutput
  | IpcCancel
  | IpcGatewayHealth
  | IpcMemoryHealth
  | IpcVersionState
  | IpcCompanionState
  | IpcCompanionAction
  | IpcHeartbeat;

// ---------------------------------------------------------------------------
// Replay protection
// ---------------------------------------------------------------------------

/**
 * Reference replay-protection tracker. Both sides MUST run one. Nonces are
 * unique-per-request random hex strings; the tracker rejects a nonce it has
 * seen within `maxAgeMs` and ages out older entries on each `check()` so the
 * table doesn't grow unbounded.
 *
 * The default 5-minute window matches the heartbeat interval × 20 — long
 * enough to catch a replayed request that crossed a heartbeat boundary, short
 * enough that a legitimately-retried request (after a pipe reconnect) isn't
 * falsely rejected.
 *
 * Note: this is NOT a substitute for transport encryption. The named pipe is
 * local-only (same machine), so replay is the realistic threat — a malicious
 * process on the box sniffing the pipe and replaying a commandRequest. The
 * tracker defeats that. For remote attackers the pipe isn't reachable.
 */
export class NonceTracker {
  private readonly seen = new Map<string, number>();
  private readonly maxAgeMs: number;

  constructor(maxAgeMs = 5 * 60 * 1000) {
    this.maxAgeMs = maxAgeMs;
  }

  /**
   * Returns true if the nonce is fresh (first time seen), false if it's a
   * replay (seen within the max-age window). Aging is performed lazily on
   * each call so we don't need a timer thread — important for the extension
   * side where we can't assume a long-lived event loop.
   */
  check(nonce: string, now = Date.now()): boolean {
    this.ageOut(now);
    if (this.seen.has(nonce)) {
      return false;
    }
    this.seen.set(nonce, now);
    return true;
  }

  /** Remove entries older than the max-age window. Called internally. */
  private ageOut(now: number): void {
    const cutoff = now - this.maxAgeMs;
    for (const [nonce, ts] of this.seen) {
      if (ts < cutoff) {
        this.seen.delete(nonce);
      }
    }
  }

  /** Number of nonces currently tracked. Exposed for tests + diagnostics. */
  get size(): number {
    return this.seen.size;
  }

  /** Clear all tracked nonces. Exposed for tests. */
  reset(): void {
    this.seen.clear();
  }
}

/**
 * Generate a fresh nonce. 16 random bytes → 32 hex chars. Collisions are
 * astronomically unlikely (2^128 space); the NonceTracker handles the rare
 * collision by rejecting the second occurrence.
 */
export function generateNonce(): string {
  return randomBytes(16).toString('hex');
}

/**
 * Type guard: is the given value a valid IpcMessage? Cheap structural check
 * on `type` + `nonce`. Used by the adapter before dispatching a handler —
 * malformed input is logged and dropped, not thrown on.
 */
export function isIpcMessage(value: unknown): value is IpcMessage {
  if (typeof value !== 'object' || value === null) return false;
  const v = value as Record<string, unknown>;
  if (typeof v.type !== 'string' || typeof v.nonce !== 'string' || typeof v.ts !== 'string') {
    return false;
  }
  const validTypes: ReadonlySet<string> = new Set<IpcMessage['type']>([
    'hello',
    'authState',
    'workspace',
    'openFiles',
    'selection',
    'taskState',
    'chatPrompt',
    'chatPromptResult',
    'workspaceReadRequest',
    'workspaceReadResult',
    'proposedEdit',
    'editReviewResult',
    'commandRequest',
    'commandReviewResult',
    'commandOutput',
    'cancel',
    'gatewayHealth',
    'memoryHealth',
    'versionState',
    'companionState',
    'companionAction',
    'heartbeat',
  ]);
  return validTypes.has(v.type);
}
