import assert from 'node:assert/strict';
import test from 'node:test';
import { normalizeAnalyzerGenomeStatus } from './analyzer-genome-status';

test('external desktop analyzer response remains unavailable instead of becoming ok:true', () => {
  assert.deepEqual(
    normalizeAnalyzerGenomeStatus({
      ok: false,
      mode: 'external_desktop_analyzer',
      source: 'Fly trading owner + uploaded desktop analyzer mirror',
      note: 'Genome reports are generated by the external desktop analyzer.',
    }),
    {
      ok: false,
      source: 'Fly trading owner + uploaded desktop analyzer mirror',
      analyzer_mode: 'external_desktop_analyzer',
      architecture_frozen: undefined,
      genome_stats: null,
      error: 'Genome reports are generated by the external desktop analyzer.',
    },
  );
});

test('real analyzer payload reports its actual counts', () => {
  const result = normalizeAnalyzerGenomeStatus({
    ok: true,
    source: 'desktop analyzer',
    analyzer_mode: 'read_only',
    genome_stats: { rows: 10 },
    discoveries: [{}, {}],
    library: { a: {}, b: {}, c: {} },
  });
  assert.equal(result.ok, true);
  assert.equal(result.discoveries_count, 2);
  assert.equal(result.library_count, 3);
});
