import {
  FOUNDER_FREE_WEEKLY_WEIGHTED_UNITS,
  FOUNDER_FREE_WINDOW_DAYS,
} from '@dcf/utils';

export const FOUNDER_FREE_MANAGED_TOKEN_CAP = FOUNDER_FREE_WEEKLY_WEIGHTED_UNITS;
export const FOUNDER_FREE_ALLOWANCE_WINDOW_DAYS = FOUNDER_FREE_WINDOW_DAYS;
