function Write-DevEnvFile {
  param(
    [string]$Path,
    [hashtable]$Vars,
    [string]$Header = "# Auto-generated by dev scripts  -  do not commit (gitignored)"
  )

  $lines = @($Header)
  foreach ($key in ($Vars.Keys | Sort-Object)) {
    $value = $Vars[$key]
    $lines += "$key=`"$value`""
  }

  $dir = Split-Path $Path -Parent
  if (-not (Test-Path $dir)) {
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
  }

  Set-Content -Path $Path -Value ($lines -join "`n") -Encoding UTF8
}

function Write-TunnelDevEnv {
  param(
    [string]$ProjectRoot,
    [string]$WebUrl,
    [string]$ApiUrl
  )

  $corsOrigins = "$WebUrl,http://localhost:3000,http://127.0.0.1:3000"
  $localApi = "http://127.0.0.1:4000"

  Write-DevEnvFile -Path (Join-Path $ProjectRoot ".env.tunnel.local") -Vars @{
    NEXTAUTH_URL         = $WebUrl
    TUNNEL_WEB_URL       = $WebUrl
    TUNNEL_API_URL       = $ApiUrl
    NEXT_PUBLIC_API_URL  = ""
    API_URL              = $localApi
    CORS_ORIGINS         = $corsOrigins
  } -Header "# Auto-generated by dev-tunnel  -  do not commit (gitignored)`n# Quick tunnel URLs change every time you restart dev-tunnel.cmd"

  Write-DevEnvFile -Path (Join-Path $ProjectRoot "apps\web\.env.local") -Vars @{
    NEXT_PUBLIC_API_URL = ""
    API_URL             = $localApi
    NEXTAUTH_URL        = $WebUrl
    TUNNEL_WEB_URL      = $WebUrl
  } -Header "# Auto-generated for Next.js client  -  restart dev-lan after tunnel URL changes`n# Browser uses same-origin /api (proxied to localhost:4000 in dev)"

  Write-DevEnvFile -Path (Join-Path $ProjectRoot "apps\api\.env.local") -Vars @{
    CORS_ORIGINS   = $corsOrigins
    API_BIND_HOST  = "127.0.0.1"
  } -Header "# Auto-generated for Nest CORS  -  restart dev-lan after tunnel URL changes"
}

function Write-LanDevEnv {
  param(
    [string]$ProjectRoot,
    [string]$LanIp,
    [string]$WebUrl,
    [string]$ApiUrl
  )

  $corsOrigins = "$WebUrl,http://localhost:3000,http://127.0.0.1:3000"
  $localApi = "http://127.0.0.1:4000"

  Write-DevEnvFile -Path (Join-Path $ProjectRoot "apps\web\.env.local") -Vars @{
    NEXT_PUBLIC_API_URL = ""
    API_URL             = $localApi
    NEXTAUTH_URL        = $WebUrl
    LAN_DEV_ORIGIN      = $LanIp
  } -Header "# Auto-generated for LAN dev  -  restart dev-lan if your Wi-Fi IP changes`n# Browser uses same-origin /api (proxied to localhost:4000 in dev)"

  Write-DevEnvFile -Path (Join-Path $ProjectRoot "apps\api\.env.local") -Vars @{
    CORS_ORIGINS  = $corsOrigins
    API_BIND_HOST = "0.0.0.0"
  } -Header "# Auto-generated for LAN dev  -  restart dev-lan if your Wi-Fi IP changes"
}

function Read-TunnelEnvFile {
  param([string]$Path)

  if (-not (Test-Path $Path)) { return $null }

  $vars = @{}
  Get-Content $Path | ForEach-Object {
    if ($_ -match '^\s*#') { return }
    if ($_ -match '^\s*([A-Za-z_][A-Za-z0-9_]*)=(.*)$') {
      $vars[$matches[1]] = $matches[2].Trim().Trim('"')
    }
  }
  return $vars
}

function Apply-TunnelEnvToProcess {
  param([hashtable]$Vars)

  foreach ($key in $Vars.Keys) {
    Set-Item -Path "env:$key" -Value $Vars[$key]
  }
}

function Test-UrlReachable {
  param(
    [string]$Url,
    [int]$TimeoutSec = 5
  )

  try {
    $response = Invoke-WebRequest -Uri $Url -UseBasicParsing -TimeoutSec $TimeoutSec
    return $response.StatusCode -ge 200 -and $response.StatusCode -lt 500
  } catch {
    return $false
  }
}
