function Read-AuthEnvFile {
  param([string]$ProjectRoot)

  $vars = @{}
  foreach ($file in @('.env', '.env.self-host')) {
    $path = Join-Path $ProjectRoot $file
    if (-not (Test-Path $path)) { continue }
    Get-Content $path | ForEach-Object {
      if ($_ -match '^\s*#') { return }
      if ($_ -match '^\s*(GOOGLE_CLIENT_ID|GOOGLE_CLIENT_SECRET|NEXTAUTH_SECRET|JWT_SECRET)=(.*)$') {
        $vars[$matches[1]] = $matches[2].Trim().Trim('"')
      }
    }
  }
  return $vars
}

function Merge-WebAuthVars {
  param(
    [string]$ProjectRoot,
    [hashtable]$Vars
  )

  $auth = Read-AuthEnvFile -ProjectRoot $ProjectRoot
  foreach ($key in @('GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET', 'NEXTAUTH_SECRET')) {
    if ($auth[$key]) {
      $Vars[$key] = $auth[$key]
    }
  }
  return $Vars
}

function Test-GoogleOAuthConfigured {
  param([string]$ProjectRoot)
  $auth = Read-AuthEnvFile -ProjectRoot $ProjectRoot
  return [bool]($auth['GOOGLE_CLIENT_ID'] -and $auth['GOOGLE_CLIENT_SECRET'])
}

function Get-LanNextAuthUrl {
  param([string]$ProjectRoot)
  # Google OAuth rejects private IP redirect URIs (10.x, 192.168.x) without extra device params.
  if (Test-GoogleOAuthConfigured -ProjectRoot $ProjectRoot) {
    return 'http://localhost:3000'
  }
  return $null
}

function Write-DevEnvFile {
  param(
    [string]$Path,
    [hashtable]$Vars,
    [string]$Header = "# Auto-generated by dev scripts  -  do not commit (gitignored)"
  )

  $lines = @($Header)
  foreach ($key in ($Vars.Keys | Sort-Object)) {
    $value = $Vars[$key]
    $lines += "$key=`"$value`""
  }

  $dir = Split-Path $Path -Parent
  if (-not (Test-Path $dir)) {
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
  }

  Set-Content -Path $Path -Value ($lines -join "`n") -Encoding UTF8
}

function Write-TunnelDevEnv {
  param(
    [string]$ProjectRoot,
    [string]$WebUrl,
    [string]$ApiUrl
  )

  $corsOrigins = "$WebUrl,http://localhost:3000,http://127.0.0.1:3000"
  $localApi = "http://127.0.0.1:4000"

  Write-DevEnvFile -Path (Join-Path $ProjectRoot ".env.tunnel.local") -Vars @{
    NEXTAUTH_URL         = $WebUrl
    TUNNEL_WEB_URL       = $WebUrl
    TUNNEL_API_URL       = $ApiUrl
    NEXT_PUBLIC_API_URL  = ""
    API_URL              = $localApi
    CORS_ORIGINS         = $corsOrigins
  } -Header "# Auto-generated by dev-tunnel  -  do not commit (gitignored)`n# Quick tunnel URLs change every time you restart dev-tunnel.cmd"

  Write-DevEnvFile -Path (Join-Path $ProjectRoot "apps\web\.env.local") -Vars (Merge-WebAuthVars -ProjectRoot $ProjectRoot -Vars @{
    NEXT_PUBLIC_API_URL = ""
    API_URL             = $localApi
    NEXTAUTH_URL        = $WebUrl
    TUNNEL_WEB_URL      = $WebUrl
  }) -Header "# Auto-generated for Next.js client  -  restart dev-lan after tunnel URL changes`n# Browser uses same-origin /api (proxied to localhost:4000 in dev)"

  Write-DevEnvFile -Path (Join-Path $ProjectRoot "apps\api\.env.local") -Vars @{
    CORS_ORIGINS   = $corsOrigins
    API_BIND_HOST  = "127.0.0.1"
  } -Header "# Auto-generated for Nest CORS  -  restart dev-lan after tunnel URL changes"
}

function Write-LanDevEnv {
  param(
    [string]$ProjectRoot,
    [string]$LanIp,
    [string]$WebUrl,
    [string]$ApiUrl
  )

  $corsOrigins = "$WebUrl,http://localhost:3000,http://127.0.0.1:3000"
  $localApi = "http://127.0.0.1:4000"
  $nextAuthUrl = Get-LanNextAuthUrl -ProjectRoot $ProjectRoot
  if (-not $nextAuthUrl) { $nextAuthUrl = $WebUrl }

  Write-DevEnvFile -Path (Join-Path $ProjectRoot "apps\web\.env.local") -Vars (Merge-WebAuthVars -ProjectRoot $ProjectRoot -Vars @{
    NEXT_PUBLIC_API_URL = ""
    API_URL             = $localApi
    NEXTAUTH_URL        = $nextAuthUrl
    LAN_DEV_ORIGIN      = $LanIp
  }) -Header "# Auto-generated for LAN dev  -  restart dev-lan if your Wi-Fi IP changes`n# Google sign-in: use http://localhost:3000 (private LAN IPs are blocked by Google)`n# Browser uses same-origin /api (proxied to localhost:4000 in dev)"

  Write-DevEnvFile -Path (Join-Path $ProjectRoot "apps\api\.env.local") -Vars @{
    CORS_ORIGINS  = $corsOrigins
    API_BIND_HOST = "0.0.0.0"
  } -Header "# Auto-generated for LAN dev  -  restart dev-lan if your Wi-Fi IP changes"
}

function Read-TunnelEnvFile {
  param([string]$Path)

  if (-not (Test-Path $Path)) { return $null }

  $vars = @{}
  Get-Content $Path | ForEach-Object {
    if ($_ -match '^\s*#') { return }
    if ($_ -match '^\s*([A-Za-z_][A-Za-z0-9_]*)=(.*)$') {
      $vars[$matches[1]] = $matches[2].Trim().Trim('"')
    }
  }
  return $vars
}

function Apply-TunnelEnvToProcess {
  param([hashtable]$Vars)

  foreach ($key in $Vars.Keys) {
    Set-Item -Path "env:$key" -Value $Vars[$key]
  }
}

function Test-UrlReachable {
  param(
    [string]$Url,
    [int]$TimeoutSec = 5
  )

  try {
    $response = Invoke-WebRequest -Uri $Url -UseBasicParsing -TimeoutSec $TimeoutSec
    return $response.StatusCode -ge 200 -and $response.StatusCode -lt 500
  } catch {
    return $false
  }
}
